### ISSUE TITLE
discord settings menu

### ISSUE THREAD

**Issue by ImCapper** [Mr-Proxy-source/proxy.github.io#1]
i cannot access the menu after enabling the theme, I do not know whether its an issue with one of my plugins being incompatible with the theme or not. but all i know is that i cant go into the normal settings for discord because of it

**Comment by Mr-Proxy-source** [comment]
I dont know for everyone other works join my support server on discord i can try help you what plugin disabling it https://discord.com/invite/pFN7tuvmnd
